CRITICAL: Linux 5.15.23
pop-os/linux pull request #122
Opened 2022-02-11 14:10 UTC by jackpot51

Changelog: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.23
CRITICAL: Fixes CVE-2022-0435

2022-02-11 23:50 UTC, leviport requested changes
On 21.10, it looks like this update breaks Plymouth (or something graphics-related) pretty severely on desktops that have Nvidia graphics. After installing this update, thelio-r2 + 3060 hangs at the BIOS splash screen and thelio-mira-b1 + 3060Ti hangs at a blank black screen. On both, blindly typing the encryption password allows me to proceed to GDM and log in. On both, hitting `Esc` does not take me to the non-graphical unlock prompt, and removing `quiet splash` doesn't seem to help either.

2022-02-15 21:45 UTC, jacobgkau commented
96763f1 fixes the Plymouth decryption screen bug on bonw14-- the decryption prompt shows up normally again.

2022-02-15 21:51 UTC, leviport commented
It's also working again on mira-b1 w/3060Ti

2022-02-16 15:44 UTC, leviport commented
Just a quick update: this is passing my tests so far. I have a few more to run through, but I will be done today.

2022-02-16 23:36 UTC, leviport approved these changes
Passing all of my tests on both Pops and Ubuntu LTS:
[pop-21.10.md](https://github.com/pop-os/linux/files/8084342/pop-21.10.md)
[pop-20.04.md](https://github.com/pop-os/linux/files/8084341/pop-20.04.md)
[ubuntu-20.04.md](https://github.com/pop-os/linux/files/8084343/ubuntu-20.04.md)

2022-02-17 21:39 UTC, merged