ALSA: hda/realtek: Add quirk for gaze17
pop-os/linux pull request #125
Opened 2022-03-04 15:20 UTC by crawfxrd

2022-03-04 23:09 UTC, jackpot51 approved these changes

2022-03-04 23:11 UTC, jackpot51 requested changes
I think we will also need to add 0x866d, that should be the NP50N[HJK]

2022-03-07 16:12 UTC, jackpot51 approved these changes

2022-03-31 19:02 UTC, crawfxrd commented
Already upstreamed.

Available in 5.17.1:

- [stable/linux@`e3a8cf32beef`](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.17.y&id=e3a8cf32beefa998fb3a17e559137b05eda01834)
- [stable/linux@`d5ec0858e782`](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.17.y&id=d5ec0858e78262d61d52931dd82e57f24a9fc073)

2022-03-31 19:02 UTC, closed without merging