Linux 5.18.8
pop-os/linux pull request #162
Opened 2022-07-04 04:59 UTC by 13r0ck

2022-07-05 23:07 UTC, n3m0-22 commented
Dependency error installing 470 on 20.04. Running `sudo apt install nvidia-kernel-source-470` first fixed the issue.

Error:
```
The following packages have unmet dependencies:
 nvidia-driver-470 : Depends: nvidia-dkms-470 (>= 470.129.06)
                     Depends: nvidia-kernel-common-470 (>= 470.129.06) but it is not going to be installed
                     Depends: nvidia-kernel-source-470 (= 470.129.06-1pop0~1656630197~20.04~c52ca60) but it is not going to be installed
                     Depends: nvidia-compute-utils-470 (= 470.129.06-1pop0~1656630197~20.04~c52ca60) but it is not going to be installed
                     Depends: nvidia-utils-470 (= 470.129.06-1pop0~1656630197~20.04~c52ca60) but it is not going to be installed
                     Depends: xserver-xorg-video-nvidia-470 (= 470.129.06-1pop0~1656630197~20.04~c52ca60) but it is not going to be installed
                     Depends: libnvidia-cfg1-470 (= 470.129.06-1pop0~1656630197~20.04~c52ca60) but it is not going to be installed
                     Recommends: libnvidia-decode-470:i386 (= 470.129.06-1pop0~1656630197~20.04~c52ca60)
                     Recommends: libnvidia-encode-470:i386 (= 470.129.06-1pop0~1656630197~20.04~c52ca60)
                     Recommends: libnvidia-ifr1-470:i386 (= 470.129.06-1pop0~1656630197~20.04~c52ca60)
                     Recommends: libnvidia-fbc1-470:i386 (= 470.129.06-1pop0~1656630197~20.04~c52ca60)
                     Recommends: libnvidia-gl-470:i386 (= 470.129.06-1pop0~1656630197~20.04~c52ca60)
```

2022-07-05 23:08 UTC, XV-02 commented
So far, this is looking good on:
- Gaze17
- Dev One
- Lemp11

However, there is an issue with the Galp5-3050 with the 515.48 Nvidia Driver:

In hybrid mode, Steam is regularly locking up, and impacting other system functions (for example, passing `reboot` in a terminal took about 30 seconds to trigger and start rebooting the machine). In Nvidia mode this wasn't an issue, and similarly, steam seemed to be working in integrated mode. 

I'm cross-testing with Ubuntu to try and limit the footprint for possible issues. It seems Galp5 specific, at the Gaze17 is happy in all three graphics modes to run Steam/Games with all three current driver versions (470.129, 510.73, and 515.48)

2022-07-05 23:27 UTC, XV-02 commented
470.129 is working with this Kernel. We'll need to _ensure_ that it is released alongside the Kernel though, as the current 470 release will not successfully build kernel modules with 5.18.x

2022-07-05 23:36 UTC, leviport commented
> We'll need to ensure that it is released alongside the Kernel though, as the current 470 release will not successfully build kernel modules with 5.18.x

470.129 was released earlier today: https://github.com/pop-os/repo-release/pull/144

2022-07-06 14:23 UTC, n3m0-22 commented
All testing on darp6 22.04 passed.

[darp6-22.04-5.18.8-kernel-tests.txt](https://github.com/pop-os/linux/files/9055607/darp6-22.04-5.18.8-kernel-tests.txt)

2022-07-06 14:25 UTC, leviport commented
Aquantia Ethernet is fine with this kernel btw. I was able to test it on my desktop at home.

2022-07-06 20:59 UTC, gangwerz commented
The galp5-1650Ti was unable to wake from suspend when in Nvidia mode while using either Pop or Ubuntu 22.04. I tried reinstalling the OS 3 times each, with little success. I was able to get the 3rd install of Pop 22.04 to suspend a couple times. But, it too failed to wake from suspend a couple times during testing.

Aside from the suspend behavior, I was able to make it through all other testing. Hybrid mode was even able to reliably wake from suspend.

I believe we are going to wait for an updated release at this time, but this was what I saw on my galp5

2022-07-06 21:40 UTC, XV-02 requested changes
So, QA is suspending testing on this Kernel release outside of diagnostic testing.

So far, we've noticed the following issues:
- On Galp5-3050 w/ Nvidia-515, Steam locks up in hybrid mode, and also effects other processes in terms of slowing their execution. 
- On Galp5-1650, the machine will not resume in dedicated graphics mode, though it will in Integrated, Hybrid, and Compute modes.
- With Ubuntu 22.04 and Nvidia-515, a usable session cannot be reached on boot.

2022-07-07 17:21 UTC, 13r0ck commented
5.18.9 & 5.18.10 do not build, so we cannot update to those either. 5.19 is still in its release candidate stage

2022-07-08 03:55 UTC, 13r0ck commented
Obsoleted by https://github.com/pop-os/linux/pull/163

2022-07-08 03:55 UTC, closed without merging