Linux 6.1.6
pop-os/linux pull request #214
Opened 2023-01-14 23:22 UTC by 13r0ck

- [ ] Test pylmouth on Mira with Nvidia before general kernel QA. 1b088b00d9f31dcecc5751e9c26007b12706f4f5 no longer cherry-picks cleanly. So hopefully it has been fixed correctly, otherwise more work will be needed.

Also this will be the first Pop!_OS kernel with rust in it! :crab:

2023-01-17 14:45 UTC, 13r0ck commented
This has now also pulled in #215. So this will also not have that vulnerability,

2023-01-18 20:59 UTC, jglathe commented
Feedback: I could build it on my build machine (ubuntu 22.10 server as VM).  Had to clean up a little after the first run that failed on dkms, but was just build debris still lying around, `git clean -df` took care of it. It is running happily on my vintage T500, will test it on a Ryzen box with NVidia card and 2 screens, too.

2023-01-18 21:11 UTC, 13r0ck commented
@jglathe awesome! Thank you!

2023-01-20 18:32 UTC, leviport requested changes
This breaks suspend on pang10 and pang11. Related fix: https://gitlab.freedesktop.org/superm1/linux/-/commit/29c666b4184a41bb07acd24551e4cd53276340b2

2023-01-20 19:02 UTC, 13r0ck commented
Cherry-picked that fix, so that shouldn't be an issue anymore

2023-01-20 22:51 UTC, leviport commented
Unfortunately that didn't fix suspend on pang10

2023-01-23 13:41 UTC, jackpot51 commented on drivers/gpio/gpiolib-acpi.c
> +			DMI_MATCH(DMI_PRODUCT_NAME, "Pangolin"),
@13r0ck this over-matches, use product version, one for pang10 and another for pang11, or find the latest version of the patch.

2023-01-26 19:48 UTC, 13r0ck commented
5ee6a55e521dc94bc2090d467b6281461f79220f should fix the pang10/12 suspend issue

2023-01-27 00:14 UTC, leviport commented
Yep, looks like that fixed pang11! :tada:

2023-01-27 22:11 UTC, leviport commented
Looks like `bcmwl-kernel-source` is throwing some DKMS errors when I try to install it. Here is the log: 
[make.log](https://github.com/pop-os/linux/files/10523474/make.log)

Guessing https://github.com/pop-os/bcmwl/ just needs an update as well?

2023-01-27 23:17 UTC, 13r0ck commented
https://github.com/pop-os/bcmwl/tree/bcmwl-rebase fixes that for me

2023-01-27 23:31 UTC, leviport commented
Yep, that fixes it for me as well

2023-01-30 19:05 UTC, XV-02 commented
@13r0ck can you elaborate on the Mira/Nvidia/Plymouth issue? 

On the first few attempts, I struggled to see a Mira/Nvidia system progress beyond entering the decryption password on boot with this kernel, which is a worry.

I've attached a log (ripped from journalctl) from the last failed attempt to boot with this Kernel PR present. 
[Failure.txt](https://github.com/pop-os/linux/files/10539071/Failure.txt)

I'm in the process of seeing whether I can find some way to induce a boot failure now I've had the system boot successfully.

2023-01-30 19:30 UTC, XV-02 commented
Previous log was after a failure to boot Old_Kern after adding this PR. This is after a failure to boot 6.1.6:
[Failure2.txt](https://github.com/pop-os/linux/files/10539234/Failure2.txt)

2023-01-30 20:00 UTC, XV-02 commented
Two back to back boot attempts, one good and one bad. They diverge at line 762 (I believe they are _literally_ identical for the first 761 line, time excepted). Not sure the implications there of. 

[good.txt](https://github.com/pop-os/linux/files/10539454/good.txt)
[bad.txt](https://github.com/pop-os/linux/files/10539455/bad.txt)

2023-01-30 20:38 UTC, jglathe commented
nvidia driver balking

2023-01-31 18:44 UTC, XV-02 commented
At least on DevOne, things are looking good. 

[DevOneLinux6-1-6.txt](https://github.com/pop-os/linux/files/10549734/DevOneLinux6-1-6.txt)

But, Mira is still misbehaving. The fact that it doesn't fail to move from Plymouth decrypt to login every time is odd to me, and guidance on desired debugging would be helpful.

2023-01-31 19:23 UTC, 13r0ck commented
@XV-02 I found a new upstream patch (f8619fafc844d77bbbf26d032453cd37abc685cc) and added it here, please let me know if that works

2023-02-01 23:28 UTC, 13r0ck commented
From my personal testing 20cfe481ed013f15293c564f51ceb276910c5588 seems to work much better

2023-02-02 19:34 UTC, dvdsk commented
No idea if this is the right place to report this but this kernel misses the zfs module. (though maybe that is supposed to be the case and the module is added later)

I installed it via `sudo apt-manage add popdev:linux-6.1.6`

2023-02-02 20:00 UTC, XV-02 commented
I'm seeing a regression in behaviour on Oryp10:

On 6.0.12, booting with lid closed and HDMI external monitor, I can decrypt the drive and log in to my user session. At that point, the machine enter sleep, and tapping the space bar wake the machine and you arrive at your user session.

On 6.1.6, booting with lid closed and HDMI external monitor, I can decrypt the drive, and at that point, the process stalls. The external monitor is blank, and log in is never reached. Opening the lid displays a Plymouth message reporting that the drive was decrypted, but doesn't proceed to login. 

Something is responsive, as tapping the spacebar on an external keyboard wake the external display, but it remains otherwise blank.

2023-02-02 21:00 UTC, XV-02 submitted a review, later dismissed
The size of the last revision is small, and the specific implications have been tested across a range of hardware (Dev One, Lemp11, Mira B4, Oryp10, Mega R1)

Outside that, things are looking good, the only caveat is that **this must be published with [Nvidia 525.85.05](https://github.com/pop-os/nvidia-graphics-drivers/pull/176).**

2023-02-02 21:22 UTC, 13r0ck commented
The last thing we are waiting for is the zfs rebase https://github.com/pop-os/zfs-linux/pull/13 (thanks @dvdsk)

2023-02-02 22:30 UTC, jackpot51 requested changes
Just want to block merge until ZFS change is approved and merged. Everything else looks good, including the latest patch to fix NVIDIA framebuffer issues

2023-02-02 23:02 UTC, n3m0-22 commented
ZFS is good to go.

2023-02-02 23:13 UTC, 13r0ck commented
@jackpot51 zfs-linux was approved and merged

2023-02-03 00:59 UTC, leviport commented
It appears that this breaks DP MST on Dev One, just like in https://github.com/pop-os/linux/issues/187

2023-02-03 01:08 UTC, 13r0ck commented
> It appears that this breaks DP MST on Dev One, just like in https://github.com/pop-os/linux/issues/187

Works on my machine

2023-02-04 00:24 UTC, leviport commented
Alright, I've got a better idea of what's going on, and I've eliminated Mesa 22.3.4 from the equation. With this kernel installed, MST breaks after suspend and resume on Dev One. So from a fresh boot, everything is working fine.

After suspending and resuming with this 6.1.6 on a fresh and updated install, MST stops working when I plug the USB-C cable in. Display settings shows both monitors I have connected, but the upstream one says "No signal" and goes back to sleep, while the downstream one never even wakes up.

When booting back into oldkern (6.0.12), both monitors work fine after suspending and resuming, then connecting the USB-C cable. I've replicated this on my own Dev One as well.

2023-02-05 14:26 UTC, lolcosmo commented
Could you enable MGLRU by default?

The kernel config option is CONFIG_LRU_GEN_ENABLED

https://www.phoronix.com/news/MGLRU-Reaches-mm-stable

2023-02-06 19:13 UTC, 13r0ck commented
@lolcosmo good find!. Currently too much of our QA has been done already on this kernel release. But I will enable it on our 6.2 series kernel and see if it passes QA.

Until the next release you could build your own kernel with that enabled
```
git clone https://github.com/pop-os/linux
cd linux
vim debian.master/config/config.commonubuntu <- this is where to enable MGLRU
sudo apt build-dep linux-system76 -y
dpkg-build-package -us -uc -b
cd ..
sudo dpkg -i *.deb
reboot
```

2023-02-07 22:46 UTC, 13r0ck commented
@leviport I cherry-picked eeda91289948ab5381847ff5d52279570d1eaeac from 6.1.9, that should fix the MST bug on DevOne

2023-02-08 04:03 UTC, jackpot51 approved these changes

2023-02-09 15:15 UTC, leviport commented
Sorry, but I don't think this fixes it. If anything, it seems worse now. Instead of just not activating either of the displays, now it sometimes makes the built-in display go black with only the mouse cursor shown, and act locked up (can't move the mouse cursor) until I unplug the USB-C cable. I tried to make these things happen while booted into oldkern (6.0.12) on the same install, but it just kept working as expected between reboots and suspend/resume cycles.

I'll do a reinstall and try again soon, just in case it was some kind of fluke.

2023-02-09 23:40 UTC, 13r0ck commented
Closed in favor of #222

2023-02-09 23:40 UTC, closed without merging