Gcc 12 jammy
pop-os/linux pull request #223
Opened 2023-02-21 01:20 UTC by 13r0ck

This reverts commit 555ca324440e8f37dcf4b3f0506dca83be8e6b64.

gcc-12 was backported to jammy by Ubuntu. This should give us a small performance improvement on the pop os kernel

2023-02-21 01:49 UTC, mmstick approved these changes

2023-02-21 14:48 UTC, jackpot51 requested changes
I did that change for 20.04. We are still backporting kernels there.

2023-02-21 15:26 UTC, 13r0ck commented
Don't we have the separate focal branch? I don't see why we should provide a slower kernel for the current release, when we can just leave that commit included on focal?

2023-02-21 15:27 UTC, jackpot51 commented
Yes, that should be possible.

2023-02-24 17:38 UTC, 13r0ck commented
This is now a part of #228

2023-02-24 17:38 UTC, closed without merging