Update debian control file for wireguard
pop-os/linux pull request #243
Opened 2023-03-22 14:53 UTC by thomas-zimmerman

Updates packaging information to note for the `wireguard` package that wireguard kernel support is present.

2023-04-11 23:12 UTC, thomas-zimmerman commented
With no update to our kernel packaging, this can be worked around with a virtual package here: https://github.com/thehunmonkgroup/wireguard-modules-virtual

2023-04-11 23:27 UTC, jacobgkau commented on debian/control
> +Provides: linux-image, fuse-module, kvm-api-4, redhat-cluster-modules, ivtv-modules, virtualbox-guest-modules [amd64], wireguard-modules (=1.0.0) ${linux:rprovides}
There used to be a comma between every item in this list, including `${linux:rprovides}`. Now there's no comma before `${linux:rprovides}`. Is that okay? I see that the build worked on Jammy, but the Debian docs do [specify](https://www.debian.org/doc/debian-policy/ch-relationships.html#syntax-of-relationship-fields) that packages in this field should be comma-separated.

2023-04-11 23:42 UTC, jacobgkau commented on debian/control
> +Provides: linux-image, fuse-module, kvm-api-4, redhat-cluster-modules, ivtv-modules, virtualbox-guest-modules [amd64], wireguard-modules (=1.0.0) ${linux:rprovides}
Added it with [1244faa](https://github.com/pop-os/linux/pull/243/commits/1244faa49c4c783a7fe521303f4fc4b6b1e4fc7c). We'll test this once it's built again.

2023-04-12 02:22 UTC, jackpot51 approved these changes

2023-04-12 17:31 UTC, jacobgkau commented
**Background investigation:**

The `wg` command is part of `wireguard-tools`.

- Without this change, installing `wireguard-tools` attempts to change the kernel version to an Ubuntu realtime kernel that presumably declares this support.
- Attempting to install the `wireguard` metapackage (which is not actually needed, but other software might depend on) pulls in `wireguard-dkms` in addition to `wireguard-tools` (but does not attempt to change the kernel version); the `wireguard-dkms` package actually doesn't "fail" to build, but the output indicates that it doesn't actually build because our kernel version is not whitelisted in its `BUILD_EXCLUSIVE` directive.
- Attempting to manually install `wireguard` plus `wireguard-modules` lists a number of Ubuntu kernel packages that provide `wireguard-modules`.

While the issue had an easy workaround of installing `wireguard-dkms` and letting it skip the build since it isn't needed, the kernel package is clearly supposed to provide `wireguard-modules` if it supports WireGuard.

2023-04-12 17:31 UTC, jacobgkau requested changes
This change doesn't seem to be working. After adding this staging branch and installing all updates, attempting to install `wireguard` or `wireguard-tools` still pull in additional dependencies as if the kernel did not support WireGuard.

Inspecting one of the other kernels that supports WireGuard (Ubuntu's realtime kernel), the `wireguard-modules` virtual package is not provided by `linux-image-x.y.z-###-realtime`, but the `linux-image-realtime` metapackage. To match, we should be providing this through `linux-image-generic` instead of the versioned package. I'll fix this.

The realtime kernel has a space between the `=` sign and the `1.0.0` inside of the parenthesis. Our file currently doesn't. I'll also fix this.

We'll need to investigate further if it still doesn't work after that.

2023-04-12 17:34 UTC, jacobgkau commented
I do see we also provide `virtualbox-guest-modules` in the versioned package while realtime provides it as part of the metapackage, and that is presumably working, so that may not be related to the issue.

2023-04-12 17:34 UTC, 13r0ck commented
[55f60b4](https://github.com/pop-os/linux/pull/243/commits/55f60b4c995f474651c0b7949819da1d7732a02e) now has a duplicate `Provides`, that is incorrect

2023-04-12 17:35 UTC, jacobgkau commented
> [55f60b4](https://github.com/pop-os/linux/pull/243/commits/55f60b4c995f474651c0b7949819da1d7732a02e) now has a duplicate `Provides`, that is incorrect

`linux-image-generic` and `linux-image-6.2.6-76060206-generic` both only have one `Provides:`, what are you talking about?

2023-04-12 17:40 UTC, 13r0ck commented
oops never mind

2023-04-12 19:42 UTC, jacobgkau commented
It's still not working on 55f60b4c995f474651c0b7949819da1d7732a02e (`wireguard(-tools)` still tries to bring in `wireguard-dkms` or other kernels.) Something else must be going on.

2023-04-12 19:47 UTC, jacobgkau commented
Doing an `apt download linux-image-generic` and examining the control file for version ~55f60b4 shows no `Provides:` line.

`linux-image-6.2.6-76060206-generic` does have a `Provides:` line (with all of the listed packages present, but in a different order than they appear in the `debian/control` source code.) I wonder how the control file's getting parsed during a build.

2023-04-12 19:53 UTC, jackpot51 commented
You have to do a `fakeroot debian/rules clean` to ensure the templates are synced with the automatically generated debian files.

2023-04-12 19:53 UTC, jackpot51 commented
@thomas-zimmerman @jacobgkau if you want, I can force push this with a commit that does the change the right way.

2023-04-12 19:54 UTC, jackpot51 commented
The right way would be to add the Provides line in debian.master/control.stub.in, then do `fakeroot debian/rules clean`, which updates debian/control.

2023-04-12 20:46 UTC, jacobgkau commented
@jackpot51 I did it the way you described. The change in `debian/control` looks identical after running that command, but `debian.master/control.stub.in` now reflects the change as well.

I see now where the versioned package's `Provides=` are being set in `debian.master/control.d/vars.generic`, too.

I got done building d824cd4 locally and it looks like it should work, once the build server is done. (Feel free to force-push if you see something else that's still wrong, though.)

2023-04-12 23:24 UTC, jacobgkau approved these changes
This is working now. Installing `wireguard` only pulls in `wireguard-tools` as a dependency, or `wireguard-tools` can now be installed manually and it doesn't pull in any dependencies. After installation, the `wg` command works. I'm able to create a`wireguard`-type interface and use `wg` to configure it.

As this is only a packaging metadata change and does not touch the actual kernel code or kernel version, full cross-hardware regression testing is not needed for this change.

2023-04-13 14:26 UTC, jackpot51 approved these changes

2023-04-13 14:26 UTC, merged